### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by randy3k** [REditorSupport/languageserver#7]
Windows does not read from STDIN non-blocking-ly. We might need to use `PEEKNAMEDPIPE ` to check that STDIN is ready.

**Comment by rwatts3** [comment]
I see that this is closed , however I still can't install via windows. Is there an alternative solution proposed that wasn't documented here ?

**Comment by randy3k** [comment]
It should be working on Windows. But you need to

1. have [Rtools](https://cran.r-project.org/bin/windows/Rtools/) installed
2. expose the path to R.exe via the PATH environmental variable.

**Comment by rwatts3** [comment]
ok i'll install rtools, 
and try to re-install

**Comment by rwatts3** [comment]
Completed step 1. 
A little confused about step 2, however I selected the PATH option in the installation wizard, wondering if this is the same as step 2. 

Either way the languageserver still does not work properly after installation.

**Comment by randy3k** [comment]
It seems that you have the server installed properly, but the language client that you are using does not work properly on Windows. To be honest, I have only tested the server with Sublime Text on Windows. The VScode and Atom clients may not work...

**Comment by randy3k** [comment]
Let me reopen it, I can confirm that that it does not play well on Atom. Maybe I should also implement a tcp socket entry point.

**Comment by rwatts3** [comment]
thank you

**Comment by randy3k** [comment]
https://github.com/REditorSupport/languageserver/commit/13c3db5017e84e7041061e82b3f9b766e6fee6cc has implemented the socket connection. I have tested on both Sublime Text and Atom.

@Ikuyadeu `vscode-r-lsp` should use the tcp connection on Windows as stdio doesn't work on Windows. `atom-ide-r` has also switched to tcp connection.

**Comment by Ikuyadeu** [comment]
@randy3k Thank you for information!
I'll fix it on this weekend.But I don't have Windows.
Could you use the `vscode-r-lsp` after I published the new version.

**Comment by randy3k** [comment]
I guess you just need to test the TCP connection on your mac/linux. Windows support should be spontaneous if the setup is correct.
